### ISSUE TITLE
Can't get runsvdir to start via runit

### ISSUE THREAD

**Issue by thomascft** [madand/runit-services#2]
I'm trying to run runsvdir via a system service as described in the [Artix Wiki](https://wiki.artixlinux.org/Main/Runit#Runit_for_user-services). I would start the user services via my `.xinitrc`, but sometimes I like to sit back and work from the tty, and I like to have pipewire running so I can listen to music. Is there any better way than running the user services after your X11 session has been started?

**Comment by madand** [comment]
I believe the correct way to start the user services in non-graphical sessions is to add `runsvdir` command to your Shell startup file, sourced when running as a login shell. For Bash this is `~/.bash_profile`.
See: https://www.gnu.org/software/bash/manual/html_node/Bash-Startup-Files.html

Closing, since this issue is not about this repo scripts.

**Comment by thomascft** [comment]
Sorry about that, would there have been a more appropriate place to post this question?

**Comment by madand** [comment]
Artix Linux [forum](https://forum.artixlinux.org/) might be the right place.
